import { initGraphQLTada } from 'gql.tada';
import type { introspection } from './graphql-env.d.ts';

// Typed GraphQL documents from the committed SDL — NO codegen step at build time; types
// come from graphql-env.d.ts (regenerated by `pnpm gen`, drift-checked in CI).
export const graphql = initGraphQLTada<{
  introspection: introspection;
  scalars: {
    DateTime: string;
    ID: string;
  };
}>();

export type { FragmentOf, ResultOf, VariablesOf } from 'gql.tada';
export { readFragment } from 'gql.tada';
