/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'ConflictError': { kind: 'OBJECT'; name: 'ConflictError'; fields: { 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'DateTime': unknown;
    'ID': unknown;
    'Idea': { kind: 'OBJECT'; name: 'Idea'; fields: { 'body': { name: 'body'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'latestPlan': { name: 'latestPlan'; type: { kind: 'OBJECT'; name: 'Plan'; ofType: null; } }; 'openQuestionCount': { name: 'openQuestionCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'questions': { name: 'questions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Question'; ofType: null; }; }; }; } }; 'research': { name: 'research'; type: { kind: 'OBJECT'; name: 'ResearchJob'; ofType: null; } }; 'source': { name: 'source'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'IdeaSource'; ofType: null; }; } }; 'sourceUrl': { name: 'sourceUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'IdeaStatus'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'IdeaSource': { name: 'IdeaSource'; enumValues: 'API' | 'SLACK' | 'WEB'; };
    'IdeaStatus': { name: 'IdeaStatus'; enumValues: 'BUILDING' | 'CAPTURED' | 'DONE' | 'PLANNED' | 'RESEARCHING' | 'SHELVED'; };
    'Int': unknown;
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'captureIdea': { name: 'captureIdea'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MutationCaptureIdeaResult'; ofType: null; }; } }; 'deleteIdea': { name: 'deleteIdea'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MutationDeleteIdeaResult'; ofType: null; }; } }; 'generateIdeaTitle': { name: 'generateIdeaTitle'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MutationGenerateIdeaTitleResult'; ofType: null; }; } }; 'startResearch': { name: 'startResearch'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MutationStartResearchResult'; ofType: null; }; } }; 'updateIdea': { name: 'updateIdea'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'MutationUpdateIdeaResult'; ofType: null; }; } }; }; };
    'MutationCaptureIdeaResult': { kind: 'UNION'; name: 'MutationCaptureIdeaResult'; fields: {}; possibleTypes: 'MutationCaptureIdeaSuccess' | 'ServerError' | 'ValidationError'; };
    'MutationCaptureIdeaSuccess': { kind: 'OBJECT'; name: 'MutationCaptureIdeaSuccess'; fields: { 'data': { name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Idea'; ofType: null; }; } }; }; };
    'MutationDeleteIdeaResult': { kind: 'UNION'; name: 'MutationDeleteIdeaResult'; fields: {}; possibleTypes: 'MutationDeleteIdeaSuccess' | 'NotFoundError' | 'ServerError'; };
    'MutationDeleteIdeaSuccess': { kind: 'OBJECT'; name: 'MutationDeleteIdeaSuccess'; fields: { 'data': { name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Idea'; ofType: null; }; } }; }; };
    'MutationGenerateIdeaTitleResult': { kind: 'UNION'; name: 'MutationGenerateIdeaTitleResult'; fields: {}; possibleTypes: 'MutationGenerateIdeaTitleSuccess' | 'NotFoundError' | 'ServerError' | 'ServiceUnavailableError'; };
    'MutationGenerateIdeaTitleSuccess': { kind: 'OBJECT'; name: 'MutationGenerateIdeaTitleSuccess'; fields: { 'data': { name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Idea'; ofType: null; }; } }; }; };
    'MutationStartResearchResult': { kind: 'UNION'; name: 'MutationStartResearchResult'; fields: {}; possibleTypes: 'MutationStartResearchSuccess' | 'NotFoundError' | 'ServerError' | 'ServiceUnavailableError'; };
    'MutationStartResearchSuccess': { kind: 'OBJECT'; name: 'MutationStartResearchSuccess'; fields: { 'data': { name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Idea'; ofType: null; }; } }; }; };
    'MutationUpdateIdeaResult': { kind: 'UNION'; name: 'MutationUpdateIdeaResult'; fields: {}; possibleTypes: 'MutationUpdateIdeaSuccess' | 'NotFoundError' | 'ServerError' | 'ValidationError'; };
    'MutationUpdateIdeaSuccess': { kind: 'OBJECT'; name: 'MutationUpdateIdeaSuccess'; fields: { 'data': { name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Idea'; ofType: null; }; } }; }; };
    'NotFoundError': { kind: 'OBJECT'; name: 'NotFoundError'; fields: { 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Plan': { kind: 'OBJECT'; name: 'Plan'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'planMd': { name: 'planMd'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'researchMd': { name: 'researchMd'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'shelveReason': { name: 'shelveReason'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'sources': { name: 'sources'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PlanSource'; ofType: null; }; }; }; } }; 'stack': { name: 'stack'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'StackItem'; ofType: null; }; }; }; } }; 'suggestion': { name: 'suggestion'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'PlanSuggestion'; ofType: null; }; } }; 'summary': { name: 'summary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'version': { name: 'version'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'PlanSource': { kind: 'OBJECT'; name: 'PlanSource'; fields: { 'firstParty': { name: 'firstParty'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'PlanSuggestion': { name: 'PlanSuggestion'; enumValues: 'PLANNED' | 'SHELVED'; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'idea': { name: 'idea'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'QueryIdeaResult'; ofType: null; }; } }; 'ideas': { name: 'ideas'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Idea'; ofType: null; }; }; }; } }; 'researchEnabled': { name: 'researchEnabled'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'QueryIdeaResult': { kind: 'UNION'; name: 'QueryIdeaResult'; fields: {}; possibleTypes: 'NotFoundError' | 'QueryIdeaSuccess' | 'ServerError'; };
    'QueryIdeaSuccess': { kind: 'OBJECT'; name: 'QueryIdeaSuccess'; fields: { 'data': { name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Idea'; ofType: null; }; } }; }; };
    'Question': { kind: 'OBJECT'; name: 'Question'; fields: { 'answer': { name: 'answer'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'defaultAnswer': { name: 'defaultAnswer'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'number': { name: 'number'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'QuestionStatus'; ofType: null; }; } }; 'text': { name: 'text'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'topic': { name: 'topic'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'why': { name: 'why'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'QuestionStatus': { name: 'QuestionStatus'; enumValues: 'ANSWERED' | 'OPEN' | 'RESOLVED' | 'SUPERSEDED'; };
    'ResearchJob': { kind: 'OBJECT'; name: 'ResearchJob'; fields: { 'attempt': { name: 'attempt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'error': { name: 'error'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'finishedAt': { name: 'finishedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'notBefore': { name: 'notBefore'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'startedAt': { name: 'startedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'ResearchJobStatus'; ofType: null; }; } }; }; };
    'ResearchJobStatus': { name: 'ResearchJobStatus'; enumValues: 'FAILED' | 'QUEUED' | 'RUNNING' | 'SUCCEEDED'; };
    'ServerError': { kind: 'OBJECT'; name: 'ServerError'; fields: { 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'ServiceUnavailableError': { kind: 'OBJECT'; name: 'ServiceUnavailableError'; fields: { 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'StackItem': { kind: 'OBJECT'; name: 'StackItem'; fields: { 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'role': { name: 'role'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'version': { name: 'version'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'String': unknown;
    'ValidationError': { kind: 'OBJECT'; name: 'ValidationError'; fields: { 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}